# Generated by Django 2.2.2 on 2020-01-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product ID', models.IntegerField()),
                ('Customer ID', models.IntegerField()),
                ('QTY', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='Created Date')),
            ],
        ),
    ]
